export type ProjectStatus = "shipped" | "in-progress";

export type Project = {
  id?: string;
  title: string;
  description: string;
  scope?: string;
  techStack: string[];
  role?: string;
  status?: ProjectStatus;
  featured?: boolean;
  demoUrl: string;
  githubUrl: string;
};

export const projects: Project[] = [
  {
    id: "PROJ-01",
    title: "EasyRide",
    description: "Full ride-hailing platform — mobile app, backend, admin dashboard",
    scope: "Real-time GPS tracking, live ride lifecycle, push notifications, admin ops dashboard",
    techStack: ["React Native", "Next.js", "MongoDB", "Firebase", "Twilio"],
    role: "Solo — architecture, all three services",
    status: "shipped",
    featured: true,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/EasyRide",
  },
  {
    id: "PROJ-02",
    title: "Virtual Medical Coder",
    description: "Independent medical NLP system extracting billing codes from clinical text.",
    scope: "Clinical NLP pipeline extracting ICD-10 codes from unstructured clinical notes",
    techStack: ["Python", "FastAPI", "React", "NLP"],
    role: "Solo — architecture & algorithm",
    status: "in-progress",
    featured: true,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/VirtualMedicalCoder",
  },
  {
    id: "PROJ-03",
    title: "Android Network Scanner",
    description: "Android application that finds nearby WiFi devices, displays IP addresses, and scans ports.",
    scope: "Local subnet discovery, open port detection & service fingerprinting",
    techStack: ["Kotlin", "Android SDK", "Network Sockets"],
    role: "Solo",
    status: "shipped",
    featured: true,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/AndroidProject",
  },
  {
    id: "PROJ-04",
    title: "True Feedback",
    description: "A simple and secure platform where users can create a unique shareable link and receive anonymous feedback.",
    scope: "Anonymous feedback platform with OTP auth & AI suggestion parsing",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "MongoDB"],
    role: "Solo",
    status: "shipped",
    featured: true,
    demoUrl: "https://true-feedback-mauve.vercel.app/",
    githubUrl: "https://github.com/MuhammadMuazAhmed/True_feedback",
  },
  {
    id: "PROJ-05",
    title: "Art Marketplace",
    description:
      "Modern marketplace for digital art with user profiles, artwork uploads, secure payments, and responsive design using MERN stack.",
    scope: "Full-stack digital art transaction ecosystem",
    techStack: ["JavaScript", "React", "Node.js", "MongoDB"],
    role: "Full Stack",
    status: "shipped",
    featured: false,
    demoUrl: "https://art-market-beta.vercel.app/",
    githubUrl: "https://github.com/MuhammadMuazAhmed/ArtMarket",
  },
  {
    id: "PROJ-06",
    title: "Hospital Management System",
    description:
      "A comprehensive healthcare management platform for streamlining patient records, appointment scheduling, and administrative workflows.",
    scope: "Patient records & appointment scheduling portal",
    techStack: ["Next.js", "React", "Tailwind CSS", "Material UI"],
    role: "Frontend & API Integration",
    status: "shipped",
    featured: false,
    demoUrl: "https://hospital-system-gon9.vercel.app/",
    githubUrl: "https://github.com/MuhammadMuazAhmed/hospital_system",
  },
  {
    id: "PROJ-07",
    title: "Perfect Academia",
    description:
      "A centralized learning platform providing structured roadmaps and curated resources across various academic and professional domains.",
    scope: "Educational roadmap generator & resource directory",
    techStack: ["React", "Tailwind CSS", "Lucide React"],
    role: "Frontend Lead",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/Perfect_Academia",
  },
  {
    id: "PROJ-08",
    title: "AI Map",
    description:
      "An experimental conversational map MVP focused on natural-language interaction with map data.",
    scope: "Conversational NLP query wrapper over OpenStreetMap",
    techStack: ["Next.js", "OpenStreetMap", "Leaflet", "Tailwind CSS"],
    role: "Solo Experiment",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/Ai_Map",
  },
  {
    id: "PROJ-09",
    title: "Netflix Pakistan Clone",
    description:
      "A responsive clone of Netflix with modern UI/UX, featuring movie browsing, search functionality, and dynamic content loading.",
    scope: "UI/UX recreation of video streaming web application",
    techStack: ["HTML", "CSS", "JavaScript"],
    role: "Frontend",
    status: "shipped",
    featured: false,
    demoUrl: "https://netflix-drab-two.vercel.app/",
    githubUrl: "https://github.com/MuhammadMuazAhmed/netflix",
  },
  {
    id: "PROJ-10",
    title: "Spotify Clone",
    description:
      "Functional music streaming application with playlist management, search features, and responsive design for seamless user experience.",
    scope: "Audio playback & playlist management client",
    techStack: ["HTML", "CSS", "JavaScript"],
    role: "Frontend",
    status: "shipped",
    featured: false,
    demoUrl: "https://spotify-three-tan.vercel.app/",
    githubUrl: "https://github.com/MuhammadMuazAhmed/Spotify",
  },
  {
    id: "PROJ-11",
    title: "X Clone",
    description:
      "A modern clone of the X (formerly Twitter) social media platform with responsive design and interactive features.",
    scope: "Social media timeline & microblogging UI",
    techStack: ["HTML", "CSS", "JavaScript"],
    role: "Frontend",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/X-clone",
  },
  {
    id: "PROJ-12",
    title: "Todo App",
    description:
      "Interactive task management application with CRUD operations, local storage, and intuitive user interface for productivity.",
    scope: "Local storage backed productivity tool",
    techStack: ["JavaScript", "React", "CSS"],
    role: "Solo",
    status: "shipped",
    featured: false,
    demoUrl: "https://todo-seven-sigma-14.vercel.app/",
    githubUrl: "https://github.com/MuhammadMuazAhmed/TODO",
  },
  {
    id: "PROJ-13",
    title: "E-commerce Web App",
    description:
      "A simple E-commerce CRUD application built with Java (Servlets & JSP) and MySQL. Demonstrates basic Create, Read, Update, and Delete operations on products.",
    scope: "Relational database CRUD server app",
    techStack: ["Java", "JSP", "Servlet", "MySQL", "JDBC"],
    role: "Backend & Database",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/EcommerceCRUD",
  },
  {
    id: "PROJ-14",
    title: "Art Marketplace Backend",
    description:
      "Backend implementation for the Art Marketplace featuring RESTful APIs, database management, and secure authentication.",
    scope: "RESTful API server with JWT authentication & MongoDB",
    techStack: ["JavaScript", "Node.js", "Express.js", "MongoDB"],
    role: "Backend Architecture",
    status: "shipped",
    featured: false,
    demoUrl: "https://art-market-backend.vercel.app/",
    githubUrl: "https://github.com/MuhammadMuazAhmed/ArtMarket_Backend",
  },
  {
    id: "PROJ-15",
    title: "Color Detector",
    description:
      "An innovative app designed to help color-blind users detect colors by simply tapping on the screen, built with Python.",
    scope: "Accessibility computer vision color identifier",
    techStack: ["Python", "OpenCV"],
    role: "Solo Developer",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/ColorDetector",
  },
  {
    id: "PROJ-16",
    title: "C++ LeetCode Solutions",
    description:
      "Collection of solved LeetCode problems implemented in C++ with optimized algorithms and data structures for competitive programming.",
    scope: "Algorithmic problem solving suite",
    techStack: ["C++", "Algorithms", "Data Structures"],
    role: "Solo",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/CppProblems",
  },
  {
    id: "PROJ-17",
    title: "Binary File Handler",
    description:
      "C++ application for efficient binary file operations including data serialization, storage, and retrieval with custom file format support.",
    scope: "Low-level binary serialization library",
    techStack: ["C++", "File I/O", "Binary Operations"],
    role: "Solo",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/Binary",
  },
  {
    id: "PROJ-18",
    title: "Academic Personnel Management",
    description:
      "Comprehensive C++ system for managing academic personnel including faculty records, course assignments, and administrative functions.",
    scope: "CLI academic administration software",
    techStack: ["C++", "OOP", "File Management"],
    role: "Solo",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/Cpp",
  },
  {
    id: "PROJ-19",
    title: "File Handling System",
    description:
      "Advanced C++ file handling library with support for various file operations, error handling, and data persistence mechanisms.",
    scope: "Persistent file stream wrapper",
    techStack: ["C++", "File I/O"],
    role: "Solo",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/FILE-HANDLING",
  },
  {
    id: "PROJ-20",
    title: "Airtime Management System",
    description:
      "C-based system for managing airtime and telecommunications data with efficient data processing and storage capabilities.",
    scope: "Embedded telecoms airtime calculation tool",
    techStack: ["C", "System Programming"],
    role: "Solo",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/airtime-project",
  },
  {
    id: "PROJ-21",
    title: "C# Design Patterns Collection",
    description:
      "Implementation of Strategy, Singleton, Decorator, Facade, and Adapter design patterns in C#.",
    scope: "Object-oriented software architecture reference implementations",
    techStack: ["C#", "Design Patterns", "OOP"],
    role: "Solo",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/STRATEGY",
  },
  {
    id: "PROJ-22",
    title: "Weather App",
    description:
      "A weather app that displays current weather conditions using OpenWeatherMap API.",
    scope: "Real-time weather API integration",
    techStack: ["JavaScript", "HTML", "CSS", "REST API"],
    role: "Solo",
    status: "shipped",
    featured: false,
    demoUrl: "https://weather-six-gold.vercel.app/",
    githubUrl: "https://github.com/MuhammadMuazAhmed/Weather",
  },
  {
    id: "PROJ-23",
    title: "Cohort",
    description:
      "An intelligent team builder that automates role definition, member allocation, and team generation.",
    scope: "Role allocation & automated team matching system",
    techStack: ["React", "Vite", "Tailwind CSS"],
    role: "Solo",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/Cohort",
  },
  {
    id: "PROJ-24",
    title: "Battle of ETL Brains",
    description:
      "An open-source quiz game designed for practicing and testing technical knowledge.",
    scope: "Interactive technical trivia game",
    techStack: ["HTML", "CSS", "JavaScript"],
    role: "Solo",
    status: "shipped",
    featured: false,
    demoUrl: "#",
    githubUrl: "https://github.com/MuhammadMuazAhmed/Battle-of-ETL-Brains",
  },
];
